# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import prosopography.models


class Migration(migrations.Migration):

    replaces = [('prosopography', '0001_initial'), ('prosopography', '0002_add_letter_m2ms'), ('prosopography', '0003_add_custom_date_fields')]

    initial = True

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('citizen', prosopography.models.SocialField(blank=True, choices=[('Y', 'Yes'), ('M', 'Maybe'), ('N', 'No'), ('U', 'Unknown')], db_index=True, default='N', max_length=1)),
                ('equestrian', prosopography.models.SocialField(blank=True, choices=[('Y', 'Yes'), ('M', 'Maybe'), ('N', 'No'), ('U', 'Unknown')], db_index=True, default='N', max_length=1)),
                ('senatorial', prosopography.models.SocialField(blank=True, choices=[('Y', 'Yes'), ('M', 'Maybe'), ('N', 'No'), ('U', 'Unknown')], db_index=True, default='N', max_length=1)),
                ('consular', prosopography.models.SocialField(blank=True, choices=[('Y', 'Yes'), ('M', 'Maybe'), ('N', 'No'), ('U', 'Unknown')], db_index=True, default='N', max_length=1)),
                ('centainty_of_id', models.PositiveSmallIntegerField(validators=[prosopography.models.valid_range])),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(blank=True, choices=[('anc', 'ancestor'), ('des', 'descendant'), ('sib', 'sibling'), ('par', 'parent'), ('chi', 'child'), ('fam', 'family group'), ('ami', 'amicus'), ('oth', 'otherwise related')], db_index=True, max_length=4)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_person', to='prosopography.Correspondent')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosopography.Correspondent')),
            ],
        ),
        migrations.AddField(
            model_name='correspondent',
            name='related_to',
            field=models.ManyToManyField(through='prosopography.Relationship', to='prosopography.Correspondent'),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='letters_to',
            field=models.ManyToManyField(related_name='letters_to', to='letters.Letter'),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='mentioned_in',
            field=models.ManyToManyField(related_name='mentioned_in', to='letters.Letter'),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='cos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='death',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='floruit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
