# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import prosopography.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('citizen', prosopography.models.SocialField(blank=True, choices=[('Y', 'Yes'), ('M', 'Maybe'), ('N', 'No'), ('U', 'Unknown')], db_index=True, default='N', max_length=1)),
                ('equestrian', prosopography.models.SocialField(blank=True, choices=[('Y', 'Yes'), ('M', 'Maybe'), ('N', 'No'), ('U', 'Unknown')], db_index=True, default='N', max_length=1)),
                ('senatorial', prosopography.models.SocialField(blank=True, choices=[('Y', 'Yes'), ('M', 'Maybe'), ('N', 'No'), ('U', 'Unknown')], db_index=True, default='N', max_length=1)),
                ('consular', prosopography.models.SocialField(blank=True, choices=[('Y', 'Yes'), ('M', 'Maybe'), ('N', 'No'), ('U', 'Unknown')], db_index=True, default='N', max_length=1)),
                ('birth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('death', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floruit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('certainty_of_id', models.PositiveSmallIntegerField(default=5, validators=[prosopography.models.valid_range])),
                ('notes', models.TextField(blank=True)),
                ('letters_to', models.ManyToManyField(blank=True, related_name='letters_to', to='letters.Letter', verbose_name='letter to')),
                ('mentioned_in', models.ManyToManyField(blank=True, related_name='mentioned_in', to='letters.Letter')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(blank=True, choices=[('anc', 'ancestor'), ('des', 'descendant'), ('sib', 'sibling'), ('par', 'parent'), ('chi', 'child'), ('fam', 'member of same familia'), ('ami', 'amicus'), ('oth', 'otherwise related')], db_index=True, max_length=4)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_person', to='prosopography.Correspondent')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosopography.Correspondent')),
            ],
        ),
        migrations.AddField(
            model_name='correspondent',
            name='related_to',
            field=models.ManyToManyField(through='prosopography.Relationship', to='prosopography.Correspondent'),
        ),
        migrations.AddField(
            model_name='aka',
            name='correspondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosopography.Correspondent'),
        ),
    ]
