# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aka',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
