# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='cos',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='floruit',
            field=models.NullBooleanField(),
        ),
    ]
