# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0002_add_letter_m2ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondent',
            name='birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='cos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='death',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='floruit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
