# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0002_add_notes_to_aka'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Correspondent',
            new_name='Person',
        ),
    ]
