# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0002_use_small_integer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='from_comum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('anc', 'ancestor'), ('des', 'descendant'), ('sib', 'sibling'), ('par', 'parent'), ('chi', 'child'), ('fam', 'member of same familia'), ('ami', 'amicus'), ('oth', 'otherwise related'), ('coc', 'Citizens of same region or municipality')], db_index=True, max_length=4),
        ),
    ]
