# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0003_add_custom_date_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondent',
            old_name='centainty_of_id',
            new_name='certainty_of_id',
        ),
    ]
