# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0003_correspondents_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aka',
            old_name='correspondent',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='aka',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('anc', 'ancestor'), ('des', 'descendant'), ('sib', 'sibling'), ('par', 'parent'), ('chi', 'child'), ('fam', 'member of same familia'), ('ami', 'amicus'), ('oth', 'otherwise related')], db_index=True, max_length=4),
        ),
    ]
