# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import prosopography.models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0004_fix_centainty_certainty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondent',
            name='certainty_of_id',
            field=models.PositiveSmallIntegerField(default=5, validators=[prosopography.models.valid_range]),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('anc', 'ancestor'), ('des', 'descendant'), ('sib', 'sibling'), ('par', 'parent'), ('chi', 'child'), ('fam', 'member of same familia'), ('ami', 'amicus'), ('oth', 'otherwise related')], db_index=True, max_length=4),
        ),
    ]
