# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosopography', '0005_topic_to_topics_for_clarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondent',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
