# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-08 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_add_contributors_through'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together=set([('pages', 'monograph', 'article', 'section')]),
        ),
    ]
