# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.PositiveSmallIntegerField()),
                ('letter', models.PositiveSmallIntegerField()),
                ('date', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='topic',
            field=models.ManyToManyField(to='letters.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='letter',
            unique_together=set([('book', 'letter')]),
        ),
    ]
