# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['book', 'letter']},
        ),
    ]
