# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_citation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='contributors',
        ),
    ]
