# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_citation'),
        ('letters', '0002_set_ordering_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='citations',
            field=models.ManyToManyField(blank=True, to='common.Citation'),
        ),
    ]
